name: Reusable Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
  Bank-Test:
    needs: test
    uses: Simon-QA17/Github_Actions_Manual/.github/workflows/calculator.yml@main
    
